## Applied Deep Learning with PyTorch

In [4]:
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\ankur\Anaconda3

  added / updated specs:
    - cudatoolkit=9.0
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.5                |           py37_0         3.0 MB
    conda-package-handling-1.3.11|           py37_0         280 KB
    cudatoolkit-9.0            |                1       339.8 MB
    ninja-1.9.0                |   py37h74a9793_0         263 KB
    pytorch-1.1.0              |py3.7_cuda90_cudnn7_1       427.2 MB  pytorch
    torchvision-0.3.0          |      py37_cu90_1         2.3 MB  pytorch
    ------------------------------------------------------------
                                           Total:       772.9 MB

The following NEW packages will be INSTALLED:

  conda-package-han~ pkgs/main/win-64::conda-package-handling-1.3.11-py3

pytorch-1.1.0        | 427.2 MB  | ######9    |  70% 
pytorch-1.1.0        | 427.2 MB  | ######9    |  70% 
pytorch-1.1.0        | 427.2 MB  | ######9    |  70% 
pytorch-1.1.0        | 427.2 MB  | ######9    |  70% 
pytorch-1.1.0        | 427.2 MB  | #######    |  70% 
pytorch-1.1.0        | 427.2 MB  | #######    |  70% 
pytorch-1.1.0        | 427.2 MB  | #######    |  70% 
pytorch-1.1.0        | 427.2 MB  | #######    |  71% 
pytorch-1.1.0        | 427.2 MB  | #######    |  71% 
pytorch-1.1.0        | 427.2 MB  | #######    |  71% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  71% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  71% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  71% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  72% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  72% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  72% 
pytorch-1.1.0        | 427.2 MB  | #######1   |  72% 
pytorch-1.1.0        | 427.2 MB  | #######2   |  72% 
pytorch-1.1.0        | 427.2

In [5]:
import torch
import torchvision

In [6]:
torch.cuda.is_available() #GPU

True

### Torch Tensors

In [7]:
# 1-D Tensor
a = torch.tensor([2,2,1])
a

tensor([2, 2, 1])

In [8]:
# 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
b

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])

In [9]:
# size of tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [10]:
# height/number of rows of b
b.shape[0]

4

In [11]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
c

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])

In [12]:
c1 = torch.tensor([2,2,1], dtype=torch.float)
c1

tensor([2., 2., 1.])

In [13]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
d

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)

In [14]:
d1 = torch.tensor([2,2,1], dtype=torch.double)
d1

tensor([2., 2., 1.], dtype=torch.float64)

In [15]:
c.mean()

tensor(2.5833)

In [16]:
d.mean()

tensor(2.5833, dtype=torch.float64)

In [17]:
c.std()

tensor(1.5050)

In [18]:
d.std()

tensor(1.5050, dtype=torch.float64)

In [26]:
# reshape b
# Note: If one of the dimension is -1, its size can be inferred
print(b)
print(b.view(-1,1))
print(b.view(-1))

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])


In [20]:
b.view(12)

tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])

In [25]:
b.view(-1,4)

tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])

In [28]:
b.view(4,3)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])

In [30]:
# assign new shape
b = b.view(1,-1)
print(b)
print(b.shape)

tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


In [31]:
# 3-D Tensor: (channels, rows, columns)
three_dim = torch.randn(2,3,4)
print("\n", three_dim)


 tensor([[[ 1.4675, -1.3071, -2.3157,  0.7819],
         [ 1.5687, -0.9729, -0.0608,  0.1688],
         [-0.4157,  0.0674, -2.2563, -2.7790]],

        [[-1.6652, -1.7491, -1.1420,  0.5440],
         [ 1.5283, -1.4834,  0.6603,  1.3510],
         [ 0.3122,  0.5996,  1.3823, -0.6017]]])


In [34]:
# reshape to 2 rows, 12 columns
three_dim.view(2,12)

tensor([[ 1.4675, -1.3071, -2.3157,  0.7819,  1.5687, -0.9729, -0.0608,  0.1688,
         -0.4157,  0.0674, -2.2563, -2.7790],
        [-1.6652, -1.7491, -1.1420,  0.5440,  1.5283, -1.4834,  0.6603,  1.3510,
          0.3122,  0.5996,  1.3823, -0.6017]])

In [35]:
three_dim.view(2,-1) #columns inferred

tensor([[ 1.4675, -1.3071, -2.3157,  0.7819,  1.5687, -0.9729, -0.0608,  0.1688,
         -0.4157,  0.0674, -2.2563, -2.7790],
        [-1.6652, -1.7491, -1.1420,  0.5440,  1.5283, -1.4834,  0.6603,  1.3510,
          0.3122,  0.5996,  1.3823, -0.6017]])

In [56]:
# matrix of random nunbers between 0 and 1
r = torch.rand(4,4)
r

tensor([[0.2924, 0.1368, 0.5313, 0.1428],
        [0.4721, 0.3172, 0.3799, 0.3454],
        [0.8866, 0.9067, 0.2391, 0.6793],
        [0.5784, 0.0160, 0.3057, 0.8239]])

In [41]:
# matrix of random nunbers from normal distribution with mean 0 and var 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 1.3931,  0.1049,  0.3366, -0.3921],
        [-0.8305, -0.9459, -0.1287,  1.9254],
        [-1.0011, -0.2169,  1.5067,  0.3002],
        [ 0.4379, -1.4758, -0.5219,  0.4506]])
torch.float32


In [42]:
# array of 5 random integers between 6 and 9 
in_array = torch.randint(6,10,(5,))
print(in_array, in_array.dtype)

tensor([6, 6, 8, 7, 8]) torch.int64


In [43]:
# 2-D array of size 3x3 
in_array2 = torch.randint(6,10,(3,5))
print(in_array2)
print(in_array2.dtype)

tensor([[8, 9, 7, 9, 9],
        [8, 9, 8, 6, 6],
        [9, 8, 7, 7, 8]])
torch.int64


In [45]:
# number of elements
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
15


In [50]:
# construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros(3, 3, dtype=torch.long)
print(z, z.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) torch.int64


In [51]:
# 3x3 of ones
o = torch.ones(3,3)
print(o, o.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [52]:
# like size of r2
r2_like = torch.randn_like(r2, dtype=torch.double) 
r2_like

tensor([[ 1.7006, -1.4259,  1.4856,  0.3513],
        [ 1.4309,  0.1480, -0.1691,  0.8195],
        [ 1.7006, -0.3261,  1.5108, -1.4637],
        [-0.4489,  0.5331,  0.6011, -1.7128]], dtype=torch.float64)

In [57]:
# add tensors, same size and dtype
add_result = torch.add(r, r2)
add_result

tensor([[ 1.6855,  0.2417,  0.8679, -0.2493],
        [-0.3584, -0.6287,  0.2512,  2.2708],
        [-0.1146,  0.6898,  1.7459,  0.9795],
        [ 1.0163, -1.4597, -0.2162,  1.2744]])

In [67]:
# in-place addition (changes value of r2)
r2.add_(r)
r2

tensor([[ 4.0246,  1.3363,  5.1184,  0.8933],
        [ 3.4181,  1.9087,  3.2907,  5.0343],
        [ 6.9779,  7.9436,  3.6589,  6.4143],
        [ 5.6432, -1.3315,  2.2296,  7.8654]])

In [68]:
r2[:,1]

tensor([ 1.3363,  1.9087,  7.9436, -1.3315])

In [69]:
r2[::2]

tensor([[4.0246, 1.3363, 5.1184, 0.8933],
        [6.9779, 7.9436, 3.6589, 6.4143]])

In [72]:
r2[:,:2]

tensor([[ 4.0246,  1.3363],
        [ 3.4181,  1.9087],
        [ 6.9779,  7.9436],
        [ 5.6432, -1.3315]])

In [73]:
r2[:3,:]

tensor([[4.0246, 1.3363, 5.1184, 0.8933],
        [3.4181, 1.9087, 3.2907, 5.0343],
        [6.9779, 7.9436, 3.6589, 6.4143]])

In [75]:
num_ten = r2[2,3]
num_ten

tensor(6.4143)

In [76]:
# 
num_ten.item() 

6.41429328918457

In [77]:
r2[2,:]

tensor([6.9779, 7.9436, 3.6589, 6.4143])